logging:
  level:
    root: INFO
spring:
  jpa:
    generate-ddl: false
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: none
  datasource:
    hikari:
      maximum-pool-size: 3
  jackson:
    visibility:
      field: any
      getter: none
      setter: none
      creator: none
      is-getter: none
    deserialization:
      fail-on-unknown-properties: true

management:
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "health,info"
