[versions]
jda-version = "5.0.0-beta.7"
lavaplayer-version = "1.3.78"
lavaplayer-fork-version = "custom-SNAPSHOT"
lp_cross-version = "0.1.1"
twittered-version = "2.21"
jetbrains-annotations-version = "24.0.1"
opus-version = "1.1.1"

names-version = "0.46.0"
jib-version = "3.3.1"
git-properties-version = "2.4.1"
sptringboot-version = "3.0.5"
sptringboot-dm-version = "1.1.0"

[libraries]
jda = { group = "net.dv8tion", name = "JDA", version.ref = "jda-version" }
lavaplayer = { group = "com.github.Walkyst.lavaplayer-fork", name = "lavaplayer", version.ref = "lavaplayer-fork-version" }
lpCross = { group = "com.github.natanbc", name = "lp-cross", version.ref = "lp_cross-version" }
twittered = { group = "io.github.redouane59.twitter", name = "twittered", version.ref = "twittered-version" }
jetbrainsAnnotations = { group = "org.jetbrains", name = "annotations", version.ref = "jetbrains-annotations-version" }
opus-api = { group = "club.minnced", name = "opus-java-api", version.ref = "opus-version" }
opus-natives = { group = "club.minnced", name = "opus-java-natives", version.ref = "opus-version" }

[bundles]
opus = ["opus-api", "opus-natives"]

[plugins]
names = { id = "com.github.ben-manes.versions", version.ref = "names-version" }
jib = { id = "com.google.cloud.tools.jib", version.ref = "jib-version" }
gitProperties = { id = "com.gorylenko.gradle-git-properties", version.ref = "git-properties-version" }
sptringboot = { id = "org.springframework.boot", version.ref = "sptringboot-version" }
sptringbootDependencyManagement = { id = "io.spring.dependency-management", version.ref = "sptringboot-dm-version" }
