[versions]
jda-version = "4.3.0_307"
lavaplayer-version = "1.3.78"
lp_cross-version = "0.1.1"
slf4j-version = "2.0.0-alpha2"
log4j2-version = "2.14.1"
log4j2-slf4j-version = "2.14.1"
unirest-version = "4.0.0-RC1"
picocli-version = "4.6.1"
jackson-version = "2.12.3"
httpclient-version = "4.5.13"
lang3-version = "3.12.0"
reflections-version = "0.9.12"
jump3r-version = "1.0.5"
twittered-version = "2.7"
jetbrains-annotations-version = "21.0.1"
kitteh-irc-version = "8.0.0"

[libraries]
jda = { group = "net.dv8tion", name = "JDA", version.ref = "jda-version" }
#jda = { group = "com.github.DV8FromTheWorld", name = "JDA", version.ref = "jda-version" }
lavaplayer = { group = "com.sedmelluq", name = "lavaplayer", version.ref = "lavaplayer-version" }
lpCross = { group = "com.github.natanbc", name = "lp-cross", version.ref = "lp_cross-version" }
jump3r = { group = "de.sciss", name = "jump3r", version.ref = "jump3r-version" }
slf4j = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j-version" }
log4j2-core = { group = "org.apache.logging.log4j", name = "log4j-core", version.ref = "log4j2-version" }
log4j2-slf4j = { group = "org.apache.logging.log4j", name = "log4j-slf4j18-impl", version.ref = "log4j2-slf4j-version" }
unirest = { group = "com.konghq", name = "unirest-java", version.ref = "unirest-version" }
picocli = { group = "info.picocli", name = "picocli", version.ref = "picocli-version" }
jackson-core = { group = "com.fasterxml.jackson.core", name = "jackson-core", version.ref = "jackson-version" }
jackson-annotations = { group = "com.fasterxml.jackson.core", name = "jackson-annotations", version.ref = "jackson-version" }
jackson-databind = { group = "com.fasterxml.jackson.core", name = "jackson-databind", version.ref = "jackson-version" }
httpclient = { group = "org.apache.httpcomponents", name = "httpclient", version.ref = "httpclient-version" }
lang3 = { group = "org.apache.commons", name = "commons-lang3", version.ref = "lang3-version" }
reflections = { group = "org.reflections", name = "reflections", version.ref = "reflections-version" }
twittered = { group = "io.github.redouane59.twitter", name = "twittered", version.ref = "twittered-version" }
jetbrainsAnnotations = { group = "org.jetbrains", name = "annotations", version.ref = "jetbrains-annotations-version" }
kittehIrc = { group = "org.kitteh.irc", name = "client-lib", version.ref = "kitteh-irc-version" }

[bundles]
jackson = ["jackson-core", "jackson-annotations", "jackson-databind"]
log4j2 = ["log4j2-core", "log4j2-slf4j"]
