name: CI

on: [ push ]

env:
  APP_JAVA_VERSION: 16

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2.3.5
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ env.APP_JAVA_VERSION }}
          cache: 'gradle'
      - name: Set gradle permissions
        run: chmod +x gradlew
      - name: Check project
        run: ./gradlew check
      - name: Push on Docker Hub
        if: success() && github.ref == 'refs/heads/main'
        run: ./gradlew jib -PdockerUsername=${{ secrets.DOCKER_USERNAME }} -PdockerPassword=${{ secrets.DOCKER_TOKEN }}
