name: CI

on: [ push ]

env:
  APP_JAVA_VERSION: 20

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ env.APP_JAVA_VERSION }}

      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: | 
            assemble
            check

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    concurrency: deploy-docker
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ env.APP_JAVA_VERSION }}

      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            jib
            -PdockerUsername=${{ secrets.DOCKER_USERNAME }}
            -PdockerPassword=${{ secrets.DOCKER_TOKEN }}
            -Djib.to.image=${{ secrets.DOCKER_IMAGE_REPO }}/rakambda/rsn-discord:latest
            -Djib.console=plain
